# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WordCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordCheck
  pod 'DropDown', '~> 2.3.2'
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'

end
